import rawCatalogue from '../data/sources.json';

/**
 * One row of src/data/sources.json, exactly as `bun run sync:sources` writes it.
 *
 * Declared by hand rather than inferred from the import, because inference
 * sees only the rows on disk. Until one entry carried `removed`, the field did
 * not exist in the inferred type at all — and a tombstone could not be typed.
 */
export type SourceRow = {
  id: string;
  name: string;
  lang: string;
  baseUrl: string;
  extPkg: string;
  extName: string;
  extVersion: string;
  extVersionCode: number;
  nsfw: boolean;
  /**
   * The day the source left the upstream extension index, as `YYYY-MM-DD`.
   * Absent on a live source; stamped by mergeCatalogue in scripts/sync-sources.ts.
   */
  removed?: string;
};

const catalogue = rawCatalogue as SourceRow[];

export type Source = SourceRow & {
  /** Readable URL segment. Unique across the catalogue — see below. */
  slug: string;
};

/**
 * Slugs, derived rather than stored.
 *
 * Names alone will not do it: 32 sources are called "MyReadingManga" and 9
 * "AnimeWorld India" (one per language each), and 14 have names with no Latin
 * characters at all — `肉視頻`, `أنمي بالكوم` — which slugify to nothing. So the
 * base is the name where it romanises and the extension package's last segment
 * where it does not, and the language code is appended only when a base is
 * ambiguous. That yields unique slugs for every entry, live and removed, with
 * no numeric fallbacks, and it is stable: it changes only when a source's name
 * or package does.
 *
 * A slug identifies one catalogue entry, never a family of them. The
 * multilingual variants are separate entries with their own ids and their own
 * extensions, so `lang: 'all'` is just another language here — spelled `multi`
 * to match the label the UI shows for it.
 */
const slugify = (raw: string) =>
  raw
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

export function withSlugs(rows: SourceRow[]): Source[] {
  const base = (s: SourceRow) =>
    slugify(s.name) || slugify(s.extPkg.split('.').pop() ?? '') || s.id;
  const seen = new Map<string, number>();
  for (const s of rows) seen.set(base(s), (seen.get(base(s)) ?? 0) + 1);
  const out = rows.map((s) => {
    const b = base(s);
    const qualifier = s.lang === 'all' ? 'multi' : s.lang.toLowerCase();
    return { ...s, slug: (seen.get(b) ?? 0) > 1 ? `${b}-${qualifier}` : b };
  });

  /* A source delisted and later re-added under a fresh id leaves a tombstone
     that computed the same slug as the new row — same name, same lang. The
     live entry keeps the slug it published; the tombstone moves aside. Live
     wins because a `/source/<slug>/` URL already in the wild must never move
     because a different source died. */
  const clash = new Map<string, number>();
  for (const s of out) clash.set(s.slug, (clash.get(s.slug) ?? 0) + 1);
  return out.map((s) =>
    s.removed && (clash.get(s.slug) ?? 0) > 1 ? { ...s, slug: `${s.slug}-removed` } : s,
  );
}

const all = withSlugs(catalogue);

/**
 * Every catalogue entry, tombstones included.
 *
 * Reports hold a bare `source_id` with no foreign key, so resolution has to
 * cover delisted rows or every report about them loses its name, its page and
 * its place in the 18+ reconcile at once. Read this rather than SOURCES
 * anywhere an existing id must still resolve.
 */
export const ALL_SOURCES: Source[] = all;

/**
 * Sources the extension index still ships. Pickers, facets, board counts, the
 * browse list and the client search index read this list, so a removed source
 * disappears from all of them while its reports keep pointing at it.
 *
 * Generated by `bun run sync:sources`. Static per build.
 */
export const SOURCES: Source[] = all.filter((s) => !s.removed);

/** Delisted entries kept on purpose. See SourceRow.removed. */
export const REMOVED_SOURCES: Source[] = all.filter((s) => s.removed);

const byId = new Map(ALL_SOURCES.map((s) => [s.id, s]));
const bySlug = new Map(ALL_SOURCES.map((s) => [s.slug, s]));
export const getSource = (id: string | null | undefined) =>
  id ? byId.get(id) : undefined;

/**
 * Like getSource, but only what the pickers can offer. Form validation answers
 * to this rather than getSource, so a crafted POST cannot file against a dead
 * source the UI never surfaced.
 */
export const getLiveSource = (id: string | null | undefined) => {
  const s = getSource(id);
  return s && !s.removed ? s : undefined;
};

/** Resolves either form, so an old `/source/<snowflake>` link keeps working. */
export const getSourceByRef = (ref: string | null | undefined) =>
  ref ? (bySlug.get(ref) ?? byId.get(ref)) : undefined;

/** Canonical path for a source page. The one place that shape is decided. */
export const sourcePath = (s: Source) => `/source/${s.slug}/`;

/**
 * `all` in the index means the source serves every language.
 *
 * Both the formatter and the result are cached: a board render asks for a
 * label about a hundred times, and constructing `Intl.DisplayNames` per call
 * was most of the cost.
 */
const displayNames = (() => {
  try {
    return new Intl.DisplayNames(['en'], { type: 'language' });
  } catch {
    return null;
  }
})();
const labelCache = new Map<string, string>();

export function langLabel(code: string): string {
  const hit = labelCache.get(code);
  if (hit !== undefined) return hit;

  let label = code.toUpperCase();
  if (code === 'all') label = 'Multi';
  else {
    const [base] = code.split('-');
    try {
      const name = displayNames?.of(base);
      if (name && name !== base) label = name;
    } catch {
      /* Intl.DisplayNames unavailable — keep the raw code */
    }
  }
  labelCache.set(code, label);
  return label;
}

/** Arabic, Hebrew and Persian source names need the right direction. */
const RTL = new Set(['ar', 'he', 'fa', 'ur']);
export const langDir = (code: string): 'rtl' | 'ltr' =>
  RTL.has(code.split('-')[0]) ? 'rtl' : 'ltr';

/** Languages present in the catalogue, most-populated first. */
export function languageFacets() {
  const counts = new Map<string, number>();
  for (const s of SOURCES) counts.set(s.lang, (counts.get(s.lang) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([code, count]) => ({ code, count, label: langLabel(code) }));
}

/** Trimmed to what the picker reads — shared so /new and /request agree. */
export const PICKER_ROWS = SOURCES.map((s) => ({
  id: s.id,
  name: s.name,
  lang: s.lang,
  nsfw: s.nsfw,
  extName: s.extName,
  extVersion: s.extVersion,
}));

export const PICKER_LANGS = Object.fromEntries(
  [...new Set(SOURCES.map((s) => s.lang))].map((code) => [code, langLabel(code)]),
);
