import catalogue from '../data/sources.json';

export type Source = (typeof catalogue)[number];

/** 310 sources, generated by `bun run sync:sources`. Static per build. */
export const SOURCES: Source[] = catalogue;

const byId = new Map(SOURCES.map((s) => [s.id, s]));
export const getSource = (id: string | null | undefined) =>
  id ? byId.get(id) : undefined;

/** `all` in the index means the source serves every language. */
export function langLabel(code: string): string {
  if (code === 'all') return 'Multi';
  const [base] = code.split('-');
  try {
    const name = new Intl.DisplayNames(['en'], { type: 'language' }).of(base);
    if (name && name !== base) return name;
  } catch {
    /* Intl.DisplayNames unavailable — fall through to the raw code */
  }
  return code.toUpperCase();
}

/** Arabic, Hebrew and Persian source names need the right direction. */
const RTL = new Set(['ar', 'he', 'fa', 'ur']);
export const langDir = (code: string): 'rtl' | 'ltr' =>
  RTL.has(code.split('-')[0]) ? 'rtl' : 'ltr';

/** Languages present in the catalogue, most-populated first. */
export function languageFacets() {
  const counts = new Map<string, number>();
  for (const s of SOURCES) counts.set(s.lang, (counts.get(s.lang) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([code, count]) => ({ code, count, label: langLabel(code) }));
}
