import catalogue from '../data/sources.json';

type CatalogueEntry = (typeof catalogue)[number];
export type Source = CatalogueEntry & {
  /** Readable URL segment. Unique across the catalogue — see below. */
  slug: string;
};

/**
 * Slugs, derived rather than stored.
 *
 * Names alone will not do it: 32 sources are called "MyReadingManga" and 9
 * "AnimeWorld India" (one per language each), and 14 have names with no Latin
 * characters at all — `肉視頻`, `أنمي بالكوم` — which slugify to nothing. So the
 * base is the name where it romanises and the extension package's last segment
 * where it does not, and the language code is appended only when a base is
 * ambiguous. That yields 310 unique slugs with no numeric fallbacks, and it is
 * stable: it changes only when a source's name or package does.
 *
 * A slug identifies one catalogue entry, never a family of them. The
 * multilingual variants are separate entries with their own ids and their own
 * extensions, so `lang: 'all'` is just another language here — spelled `multi`
 * to match the label the UI shows for it.
 */
const slugify = (raw: string) =>
  raw
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

function withSlugs(rows: CatalogueEntry[]): Source[] {
  const base = (s: CatalogueEntry) =>
    slugify(s.name) || slugify(s.extPkg.split('.').pop() ?? '') || s.id;
  const seen = new Map<string, number>();
  for (const s of rows) seen.set(base(s), (seen.get(base(s)) ?? 0) + 1);
  return rows.map((s) => {
    const b = base(s);
    const qualifier = s.lang === 'all' ? 'multi' : s.lang.toLowerCase();
    return { ...s, slug: (seen.get(b) ?? 0) > 1 ? `${b}-${qualifier}` : b };
  });
}

/** 310 sources, generated by `bun run sync:sources`. Static per build. */
export const SOURCES: Source[] = withSlugs(catalogue);

const byId = new Map(SOURCES.map((s) => [s.id, s]));
const bySlug = new Map(SOURCES.map((s) => [s.slug, s]));
export const getSource = (id: string | null | undefined) =>
  id ? byId.get(id) : undefined;

/** Resolves either form, so an old `/source/<snowflake>` link keeps working. */
export const getSourceByRef = (ref: string | null | undefined) =>
  ref ? (bySlug.get(ref) ?? byId.get(ref)) : undefined;

/** Canonical path for a source page. The one place that shape is decided. */
export const sourcePath = (s: Source) => `/source/${s.slug}/`;

/**
 * `all` in the index means the source serves every language.
 *
 * Both the formatter and the result are cached: a board render asks for a
 * label about a hundred times, and constructing `Intl.DisplayNames` per call
 * was most of the cost.
 */
const displayNames = (() => {
  try {
    return new Intl.DisplayNames(['en'], { type: 'language' });
  } catch {
    return null;
  }
})();
const labelCache = new Map<string, string>();

export function langLabel(code: string): string {
  const hit = labelCache.get(code);
  if (hit !== undefined) return hit;

  let label = code.toUpperCase();
  if (code === 'all') label = 'Multi';
  else {
    const [base] = code.split('-');
    try {
      const name = displayNames?.of(base);
      if (name && name !== base) label = name;
    } catch {
      /* Intl.DisplayNames unavailable — keep the raw code */
    }
  }
  labelCache.set(code, label);
  return label;
}

/** Arabic, Hebrew and Persian source names need the right direction. */
const RTL = new Set(['ar', 'he', 'fa', 'ur']);
export const langDir = (code: string): 'rtl' | 'ltr' =>
  RTL.has(code.split('-')[0]) ? 'rtl' : 'ltr';

/** Languages present in the catalogue, most-populated first. */
export function languageFacets() {
  const counts = new Map<string, number>();
  for (const s of SOURCES) counts.set(s.lang, (counts.get(s.lang) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([code, count]) => ({ code, count, label: langLabel(code) }));
}
