import { desc, sql } from 'drizzle-orm';
import {
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import { PROBLEM_KEYS } from '../problems';

/**
 * There is deliberately no `sources` table.
 *
 * The catalogue is static per build (src/data/sources.json, generated by
 * `bun run sync:sources`), so keeping a copy in D1 would only create drift and
 * a sync step. Instead the two source attributes the board filters on — `lang`
 * and `nsfw` — are denormalised onto the report row at creation time. That is
 * honest rather than lazy: a report describes a source *as it was when filed*,
 * which is why `extVersion` is captured the same way.
 */

export const KINDS = [
  'bug', // 01_report_issue.yml
  'request', // 02_request_source.yml
  'domain', // 03_report_url_change.yml
  'dead', // 04_report_dead_source.yml
  'feature', // 05_request_feature.yml
  'meta', // 06_request_meta.yml
  'removal', // 07_request_removal.yml
] as const;

/** Where it breaks. Mirrors the extension tester's probe stages. */
export const STAGES = ['browse', 'episodes', 'video'] as const;

/** Why it breaks. Taken from the labels actually in use on the repo. */
export const CAUSES = [
  'redesign', // 35 issues
  'domain', // 30
  'cloudflare', // 24
  'down', // 14
  'geo', // 13
  'extractor', // "No available videos" — the most common bug title
  'other',
] as const;

export const STATUSES = [
  'open',
  'confirmed',
  'in_progress',
  'fixed',
  'wont_fix',
  'duplicate',
] as const;

/** Statuses that still count as live demand — the dedupe window. */
export const OPEN_STATUSES = ['open', 'confirmed', 'in_progress'] as const;

/**
 * Closed without a fix. With OPEN_STATUSES and `'fixed'` these three name the
 * whole of STATUSES from one place, so the boards' three views and github.ts's
 * CLOSED_STATUSES cannot disagree about which status lands where.
 */
export const OTHER_STATUSES = ['wont_fix', 'duplicate'] as const;

/**
 * Staff tiers. `mod` moves reports along; `admin` also changes settings and
 * hands out these levels. Ownership is deliberately *not* a tier — it comes
 * from OWNER_DISCORD_ID in the environment, so no dashboard action can grant
 * it and a bad grant is always recoverable.
 */
export const STAFF_LEVELS = ['mod', 'admin'] as const;
export type StaffLevel = (typeof STAFF_LEVELS)[number];

export const users = sqliteTable('users', {
  discordId: text('discord_id').primaryKey(),
  username: text('username').notNull(),
  avatarHash: text('avatar_hash'),
  /** Decoded from the Discord snowflake — no extra OAuth scope needed. */
  accountCreatedAt: integer('account_created_at').notNull(),
  guildJoinedAt: integer('guild_joined_at'),
  /**
   * Staff comes from two independent sources, kept in separate columns so
   * neither can quietly erase the other: `discord_level` is recomputed from
   * the member's roles at every login, `manual_level` is granted by hand and
   * survives any role change. The effective level is the higher of the two.
   */
  discordLevel: text('discord_level', { enum: STAFF_LEVELS }),
  manualLevel: text('manual_level', { enum: STAFF_LEVELS }),
  /**
   * Blocked from writing, regardless of guild membership or account age.
   *
   * The gate that decides whether someone may post was previously computed
   * once at login and never revisited, so there was no way to stop an abusive
   * account short of waiting for it to sign in again. This column is read on
   * every write, which is what makes revocation immediate.
   */
  banned: integer('banned', { mode: 'boolean' }).notNull().default(false),
  firstSeen: integer('first_seen').notNull().default(sql`(unixepoch())`),
  lastLogin: integer('last_login').notNull().default(sql`(unixepoch())`),
});

export const reports = sqliteTable(
  'reports',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    kind: text('kind', { enum: KINDS }).notNull(),

    /** Null for `request` — the source does not exist yet. */
    sourceId: text('source_id'),
    proposedName: text('proposed_name'),
    proposedUrl: text('proposed_url'),

    /**
     * Where the site moved to, for `domain` reports. Deliberately not
     * `proposed_url`: that column carries the request dedupe index, so sharing
     * it would make a domain change collide with an unrelated source request.
     * Maps to the `link` field of 03_report_url_change.yml on promotion.
     */
    newUrl: text('new_url'),

    /** Denormalised from the catalogue so the board can filter in SQL. */
    lang: text('lang').notNull(),
    nsfw: integer('nsfw', { mode: 'boolean' }).notNull().default(false),

    stage: text('stage', { enum: STAGES }),
    cause: text('cause', { enum: CAUSES }),

    /**
     * Which of the seven problems on /new this is — the dedupe key.
     *
     * `kind` cannot do that job: five of the seven problems are `kind: 'bug'`,
     * so deduping on kind alone made a source's *second* distinct failure
     * impossible to file and silently upvoted an unrelated report instead.
     * Null only on rows that predate the column and on kinds with no source.
     */
    problem: text('problem', { enum: PROBLEM_KEYS }),

    title: text('title').notNull(),
    body: text('body'),

    status: text('status', { enum: STATUSES }).notNull().default('open'),
    reporterId: text('reporter_id')
      .notNull()
      .references(() => users.discordId),

    /**
     * The reporter's actual setup. Mandatory on new reports: "which version"
     * is the first thing a maintainer asks, and a stale extension is the most
     * common non-bug, so it is cheaper to collect than to chase.
     */
    extVersion: text('ext_version'),
    appName: text('app_name'),
    appVersion: text('app_version'),
    githubIssue: integer('github_issue'),
    duplicateOf: integer('duplicate_of'),

    /**
     * Denormalised counter, written in the same D1 batch as the vote row.
     *
     * The board's whole job is ORDER BY demand, and a counter keeps that an
     * index range scan rather than an aggregate join on every render — which
     * matters because D1 reads all hit one primary region. It is only that
     * cheap while `reports_board` below leads with the same columns the board
     * filters on; when the index led with `kind` instead, the plan added a temp
     * B-tree sort and the claim this comment used to make ("a single indexed
     * scan") was simply false.
     *
     * Because it is denormalised it can drift, so it is moved *only* by
     * lib/vote.ts, in the same batch as the vote row, and never seeded at
     * insert time.
     */
    votes: integer('votes').notNull().default(0),

    createdAt: integer('created_at').notNull().default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').notNull().default(sql`(unixepoch())`),
    statusChangedAt: integer('status_changed_at'),

    /**
     * When this report was announced to Discord as *demand* — so a threshold
     * alert fires once.
     */
    announcedAt: integer('announced_at'),

    /**
     * When its fix was announced. A separate column on purpose: sharing
     * `announced_at` meant a demand alert permanently consumed the fix
     * announcement, so the reports whose fix was most worth telling people
     * about were exactly the ones that never got told.
     */
    fixAnnouncedAt: integer('fix_announced_at'),

    /**
     * When a moderator sent this to GitHub. A third claim column alongside the
     * two above, and for the same reason: promotion opens an issue upstream,
     * which is not undoable, so the click has to be claimed before the redirect
     * rather than trusted not to happen twice. A double-tap on a phone would
     * otherwise file two issues for one report.
     */
    promotedAt: integer('promoted_at'),

    statusNote: text('status_note'),
  },
  (t) => [
    /**
     * The core mechanic: one open report per source per *problem*. A second
     * person hitting the same breakage is routed to upvote rather than file,
     * which is what turns vote count into a usable priority number — while a
     * genuinely different failure on the same source can still be filed.
     */
    uniqueIndex('reports_open_per_source_problem')
      .on(t.sourceId, t.kind, t.problem)
      .where(sql`status IN ('open', 'confirmed', 'in_progress') AND source_id IS NOT NULL`),

    /** Same rule for source requests, keyed on the proposed URL. */
    uniqueIndex('reports_open_per_proposed_url')
      .on(t.proposedUrl)
      .where(sql`status IN ('open', 'confirmed', 'in_progress') AND proposed_url IS NOT NULL`),

    /** One open feature per source per title. Prevents duplicate asks splitting votes. */
    uniqueIndex('reports_open_feature_per_source_title')
      .on(t.sourceId, t.title)
      .where(sql`kind = 'feature' AND status IN ('open', 'confirmed', 'in_progress')`),

    /**
     * Column order is the board's query, in order: both boards filter
     * `status IN (...)` and (unless NSFW is on) `nsfw = 0`, then sort by votes
     * descending with `created_at` as the tiebreak. `kind` comes last because
     * it arrives as an `IN` list, which cannot be used as an equality seek —
     * leading with it forced a temp B-tree for every board render.
     */
    index('reports_board').on(t.status, t.nsfw, desc(t.votes), t.createdAt, t.kind),
    /**
     * The board's default sort, and the reason it needs a *partial* index.
     *
     * `reports_board` above leads with `status`, which the board supplies as a
     * three-value `IN` list — so SQLite runs three separate seeks and cannot
     * merge them in `votes desc` order. The plan came out as
     * `SEARCH reports USING INDEX reports_board (status=? AND nsfw=?)` plus
     * `USE TEMP B-TREE FOR ORDER BY`, and no reordering of those columns
     * removes it while `status` is a list rather than an equality.
     *
     * Moving the list into the index's own predicate is what fixes it: every
     * row in this index is already open, so there is nothing left to seek on
     * and the scan already comes out in sort order. Verified with
     * EXPLAIN QUERY PLAN that the planner picks it unhinted —
     * `SEARCH reports USING INDEX reports_board_open (nsfw=?)`, no temp B-tree.
     *
     * It covers the default `demand` sort with 18+ off, which is the great
     * majority of board views. The 18+ path has no equality on `nsfw`, and the
     * `recent` and `stalled` sorts want a different column order, so those fall
     * back to `reports_board` and still sort correctly. Three more partial
     * indexes to flatten three rarer paths is not a trade worth making on a
     * 468-row table; revisit if the board ever grows enough for it to show.
     *
     * `reports_board` stays: it is what serves the covering `count(*)` behind
     * the pager, on both the 18+ and the non-18+ path.
     */
    index('reports_board_open')
      .on(t.nsfw, desc(t.votes), t.createdAt, t.kind)
      .where(sql`status IN ('open', 'confirmed', 'in_progress')`),
    /** Covers the three header tallies without touching the table. */
    index('reports_tallies').on(t.status, t.kind, t.createdAt),
    index('reports_by_source').on(t.sourceId),
    index('reports_by_reporter').on(t.reporterId),
    index('reports_by_age').on(t.status, t.createdAt),
    /**
     * Unique, not merely indexed. Inbound sync resolves an issue to a report
     * through this column, so two reports claiming one issue number would make
     * "which report does issue 412 mean" unanswerable — and the sync would
     * update whichever row the planner happened to return first. Partial
     * because the overwhelming majority of reports have no issue at all.
     */
    uniqueIndex('reports_by_issue')
      .on(t.githubIssue)
      .where(sql`github_issue IS NOT NULL`),
  ],
);

export const votes = sqliteTable(
  'votes',
  {
    reportId: integer('report_id')
      .notNull()
      .references(() => reports.id, { onDelete: 'cascade' }),
    discordId: text('discord_id')
      .notNull()
      .references(() => users.discordId, { onDelete: 'cascade' }),
    createdAt: integer('created_at').notNull().default(sql`(unixepoch())`),
  },
  (t) => [
    // One vote per person per report, enforced by the key itself.
    primaryKey({ columns: [t.reportId, t.discordId] }),
    index('votes_by_user').on(t.discordId),
  ],
);

/**
 * Replaces push notifications. Discord announcements are broadcast, so nobody
 * can tell which fix was theirs; an unread flag on /me closes that loop with
 * no permission prompt and no personal data.
 */
export const notifications = sqliteTable(
  'notifications',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    userId: text('user_id')
      .notNull()
      .references(() => users.discordId, { onDelete: 'cascade' }),
    reportId: integer('report_id')
      .notNull()
      .references(() => reports.id, { onDelete: 'cascade' }),
    kind: text('kind', { enum: ['status_changed', 'promoted', 'duplicate'] }).notNull(),
    detail: text('detail'),
    createdAt: integer('created_at').notNull().default(sql`(unixepoch())`),
    readAt: integer('read_at'),
  },
  (t) => [index('notifications_unread').on(t.userId, t.readAt)],
);

export type User = typeof users.$inferSelect;
export type Report = typeof reports.$inferSelect;
export type NewReport = typeof reports.$inferInsert;
export type Notification = typeof notifications.$inferSelect;

/**
 * Runtime configuration, editable from /admin.
 *
 * Key/value rather than one wide row: the settings this grows into are a
 * ragged set (a URL here, a threshold there), and a redeploy to add a column
 * is exactly the friction the dashboard exists to remove. Every read falls
 * back to an environment default, so an empty table is a working config.
 */
export const settings = sqliteTable('settings', {
  key: text('key').primaryKey(),
  value: text('value'),
  updatedAt: integer('updated_at').notNull().default(sql`(unixepoch())`),
  updatedBy: text('updated_by'),
});

/**
 * Who did what. Staff powers on a community board are only as trustworthy as
 * they are visible, and "who marked this fixed" is the first question asked
 * when a report is wrong.
 */
export const audit = sqliteTable(
  'audit',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    actorId: text('actor_id').notNull(),
    actorName: text('actor_name').notNull(),
    action: text('action').notNull(),
    target: text('target'),
    detail: text('detail'),
    createdAt: integer('created_at').notNull().default(sql`(unixepoch())`),
  },
  (t) => [index('audit_recent').on(t.createdAt)],
);

/**
 * What the GitHub sync last saw, one row per upstream issue.
 *
 * This is the memory that lets a full-state pass behave like a stream of
 * events. Comparing the *previously observed* upstream state against the
 * current one is what distinguishes "someone reopened this" from "this was
 * never closed" — and that distinction is load-bearing, because this install
 * has no write access upstream, so a report fixed here leaves its issue open
 * there indefinitely. Without the comparison, a sync that acted on
 * disagreement would revert every moderator decision on every pass.
 *
 * It is a record, not a cursor. Losing the table degrades the next pass to
 * first-sight behaviour — closures still apply, one round of reopens is missed
 * — rather than stalling the sync, which is why nothing here needs backing up.
 */
export const githubIssues = sqliteTable(
  'github_issues',
  {
    /** The upstream issue number, which is stable and unique per repo. */
    number: integer('number').primaryKey(),
    title: text('title').notNull(),
    state: text('state', { enum: ['open', 'closed'] }).notNull(),
    /** GitHub's own closed-reason. Preferred over labels, which get renamed. */
    stateReason: text('state_reason'),
    /** The issue's own updated_at, for ordering rather than for triggering. */
    updatedAt: integer('updated_at'),
    /**
     * The issue's labels, JSON. Kept so /review can re-derive a kind and cause
     * for an issue a moderator adopts later, without going back to the GitHub
     * API from inside a page render.
     */
    labels: text('labels'),
    /** 👍 count, so an adoption seeds votes the way the backlog import did. */
    reactions: integer('reactions').notNull().default(0),
    /** Null while unmatched; that is exactly what /review lists. */
    reportId: integer('report_id').references(() => reports.id, { onDelete: 'set null' }),
    seenAt: integer('seen_at').notNull().default(sql`(unixepoch())`),
    /**
     * Set when a moderator decides an issue needs no report. Deliberately a
     * flag rather than a delete: removing the row would make the next pass
     * treat the issue as never-seen and put it straight back in the queue.
     */
    dismissedAt: integer('dismissed_at'),
  },
  (t) => [
    /** The /review queue: unmatched, not yet dismissed. */
    index('github_issues_unmatched').on(t.reportId, t.dismissedAt),
  ],
);

export type GithubIssue = typeof githubIssues.$inferSelect;
