import { sql } from 'drizzle-orm';
import {
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';

/**
 * There is deliberately no `sources` table.
 *
 * The catalogue is static per build (src/data/sources.json, generated by
 * `bun run sync:sources`), so keeping a copy in D1 would only create drift and
 * a sync step. Instead the two source attributes the board filters on — `lang`
 * and `nsfw` — are denormalised onto the report row at creation time. That is
 * honest rather than lazy: a report describes a source *as it was when filed*,
 * which is why `extVersion` is captured the same way.
 */

export const KINDS = [
  'bug', // 01_report_issue.yml
  'request', // 02_request_source.yml
  'domain', // 03_report_url_change.yml
  'dead', // 04_report_dead_source.yml
  'feature', // 05_request_feature.yml
  'meta', // 06_request_meta.yml
  'removal', // 07_request_removal.yml
] as const;

/** Where it breaks. Mirrors the extension tester's probe stages. */
export const STAGES = ['browse', 'episodes', 'video'] as const;

/** Why it breaks. Taken from the labels actually in use on the repo. */
export const CAUSES = [
  'redesign', // 35 issues
  'domain', // 30
  'cloudflare', // 24
  'down', // 14
  'geo', // 13
  'extractor', // "No available videos" — the most common bug title
  'other',
] as const;

export const STATUSES = [
  'open',
  'confirmed',
  'in_progress',
  'fixed',
  'wont_fix',
  'duplicate',
] as const;

/** Statuses that still count as live demand — the dedupe window. */
export const OPEN_STATUSES = ['open', 'confirmed', 'in_progress'] as const;

export const users = sqliteTable('users', {
  discordId: text('discord_id').primaryKey(),
  username: text('username').notNull(),
  avatarHash: text('avatar_hash'),
  /** Decoded from the Discord snowflake — no extra OAuth scope needed. */
  accountCreatedAt: integer('account_created_at').notNull(),
  guildJoinedAt: integer('guild_joined_at'),
  isMaintainer: integer('is_maintainer', { mode: 'boolean' }).notNull().default(false),
  firstSeen: integer('first_seen').notNull().default(sql`(unixepoch())`),
  lastLogin: integer('last_login').notNull().default(sql`(unixepoch())`),
});

export const reports = sqliteTable(
  'reports',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    kind: text('kind', { enum: KINDS }).notNull(),

    /** Null for `request` — the source does not exist yet. */
    sourceId: text('source_id'),
    proposedName: text('proposed_name'),
    proposedUrl: text('proposed_url'),

    /**
     * Where the site moved to, for `domain` reports. Deliberately not
     * `proposed_url`: that column carries the request dedupe index, so sharing
     * it would make a domain change collide with an unrelated source request.
     * Maps to the `link` field of 03_report_url_change.yml on promotion.
     */
    newUrl: text('new_url'),

    /** Denormalised from the catalogue so the board can filter in SQL. */
    lang: text('lang').notNull(),
    nsfw: integer('nsfw', { mode: 'boolean' }).notNull().default(false),

    stage: text('stage', { enum: STAGES }),
    cause: text('cause', { enum: CAUSES }),

    title: text('title').notNull(),
    body: text('body'),

    status: text('status', { enum: STATUSES }).notNull().default('open'),
    reporterId: text('reporter_id')
      .notNull()
      .references(() => users.discordId),

    extVersion: text('ext_version'),
    githubIssue: integer('github_issue'),
    duplicateOf: integer('duplicate_of'),

    /**
     * Denormalised counter, written in the same D1 batch as the vote row.
     * The board's whole job is ORDER BY demand; a counter keeps that a single
     * indexed scan instead of an aggregate join on every render, which matters
     * because D1 reads all hit one primary region.
     */
    votes: integer('votes').notNull().default(0),

    createdAt: integer('created_at').notNull().default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').notNull().default(sql`(unixepoch())`),
    statusChangedAt: integer('status_changed_at'),
  },
  (t) => [
    /**
     * The core mechanic: one open report per source per kind. A second person
     * hitting the same breakage is routed to upvote rather than file, which is
     * what turns vote count into a usable priority number.
     */
    uniqueIndex('reports_open_per_source_kind')
      .on(t.sourceId, t.kind)
      .where(sql`status IN ('open', 'confirmed', 'in_progress') AND source_id IS NOT NULL`),

    /** Same rule for source requests, keyed on the proposed URL. */
    uniqueIndex('reports_open_per_proposed_url')
      .on(t.proposedUrl)
      .where(sql`status IN ('open', 'confirmed', 'in_progress') AND proposed_url IS NOT NULL`),

    index('reports_board').on(t.kind, t.status, t.votes),
    index('reports_by_source').on(t.sourceId),
    index('reports_by_reporter').on(t.reporterId),
    index('reports_by_age').on(t.status, t.createdAt),
    index('reports_by_issue').on(t.githubIssue),
  ],
);

export const votes = sqliteTable(
  'votes',
  {
    reportId: integer('report_id')
      .notNull()
      .references(() => reports.id, { onDelete: 'cascade' }),
    discordId: text('discord_id')
      .notNull()
      .references(() => users.discordId, { onDelete: 'cascade' }),
    createdAt: integer('created_at').notNull().default(sql`(unixepoch())`),
  },
  (t) => [
    // One vote per person per report, enforced by the key itself.
    primaryKey({ columns: [t.reportId, t.discordId] }),
    index('votes_by_user').on(t.discordId),
  ],
);

/**
 * Replaces push notifications. Discord announcements are broadcast, so nobody
 * can tell which fix was theirs; an unread flag on /me closes that loop with
 * no permission prompt and no personal data.
 */
export const notifications = sqliteTable(
  'notifications',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    userId: text('user_id')
      .notNull()
      .references(() => users.discordId, { onDelete: 'cascade' }),
    reportId: integer('report_id')
      .notNull()
      .references(() => reports.id, { onDelete: 'cascade' }),
    kind: text('kind', { enum: ['status_changed', 'promoted', 'duplicate'] }).notNull(),
    detail: text('detail'),
    createdAt: integer('created_at').notNull().default(sql`(unixepoch())`),
    readAt: integer('read_at'),
  },
  (t) => [index('notifications_unread').on(t.userId, t.readAt)],
);

export type User = typeof users.$inferSelect;
export type Report = typeof reports.$inferSelect;
export type NewReport = typeof reports.$inferInsert;
export type Notification = typeof notifications.$inferSelect;
