/**
 * Imports the existing GitHub issue backlog into the tracker.
 *
 * Doubles as the seed for local development and as the real migration path if
 * the tool gets adopted: every open issue becomes a report, and its 👍 reaction
 * count becomes the starting vote weight — reactions are exactly the demand
 * signal this board replaces, so nothing is invented.
 *
 *   gh api -X GET repos/yuzono/anime-extensions/issues -f state=all -f per_page=100 \
 *     --paginate --jq '[.[] | {number, title, state, createdAt: .created_at,
 *       closedAt: .closed_at, body, labels: [.labels[].name],
 *       up: .reactions["+1"], comments}]' > issues_full.json
 *   bun scripts/import-issues.ts issues_full.json > seeds/seed.sql
 */

/**
 * The title, label and language heuristics live in src/lib/github.ts, which the
 * live sync uses too. They were defined here first, but a second copy in the
 * Worker would drift from this one — and a regenerated seed that deduped
 * differently from the running site would not error, it would just be wrong.
 */
import {
  causeOf,
  headOf,
  kindOf,
  sourceLinkFromBody,
  langOf,
  matchSource,
  norm,
  nsfwFor,
  problemOf,
  stageOf,
} from '../src/lib/github';
import { problemKeyFor } from '../src/lib/problems';
import { getSource } from '../src/lib/sources';

type Issue = {
  number: number;
  title: string;
  state: 'open' | 'closed';
  createdAt: string;
  closedAt: string | null;
  labels: string[];
  up: number;
  comments: number;
  /**
   * Optional, because the first exports of this file did not include it — and
   * that omission is why every imported request lost the site's address. The
   * `--jq` above now asks for it; an older export still imports, just without
   * the addresses.
   */
  body?: string | null;
};

const file = process.argv[2];
if (!file) throw new Error('usage: bun scripts/import-issues.ts <issues.json>');
const issues: Issue[] = await Bun.file(file).json();

const esc = (v: string) => `'${v.replace(/'/g, "''")}'`;
const nul = (v: string | null | undefined) => (v == null ? 'NULL' : esc(v));
const ts = (d: string) => Math.floor(new Date(d).getTime() / 1000);

/* --- emit ----------------------------------------------------------------- */
const out: string[] = [
  '-- Generated by scripts/import-issues.ts. Vote counts are real 👍 reactions.',
  '--',
  '-- DESTRUCTIVE, AND LOCAL ONLY. The next three DELETEs empty every table this',
  '-- file writes, so running it against the deployed database would erase real',
  '-- reports and real votes. `bun run db:seed` pins --local for that reason;',
  '-- never add --remote to it.',
  'PRAGMA defer_foreign_keys = true;',
  'DELETE FROM notifications; DELETE FROM votes; DELETE FROM reports; DELETE FROM users;',
  `INSERT INTO users (discord_id, username, account_created_at)
     VALUES ('0', 'imported-from-github', 0);`,
];

const stats = { matched: 0, unmatched: 0, byKind: {} as Record<string, number>, votes: 0 };
const seenOpen = new Set<string>();

for (const iss of issues) {
  const kind = kindOf(iss.labels);
  const sourceId = kind === 'request' ? undefined : matchSource(iss.title);
  const lang = langOf(iss.title, sourceId);
  // A request's title is the source's name, so say what's being asked for.
  const problemText =
    kind === 'request' ? `Add ${headOf(iss.title).slice(0, 70) || 'this source'}` : problemOf(iss.title);
  const cause =
    kind === 'bug' || kind === 'domain' || kind === 'dead' ? causeOf(iss.labels, problemText) : null;
  const stage = cause ? stageOf(problemText, cause) : null;
  // The dedupe key the board actually uses, from the one function the migration
  // and this script both answer to — see problemKeyFor in src/lib/problems.ts.
  // A regenerated seed that disagreed with the backfilled production rows would
  // not error; it would just dedupe differently.
  const problemKey = problemKeyFor(kind, stage, cause, !!sourceId);
  // The catalogue decides for a matched source; the label only speaks when
  // there is nothing to match. This line used to read
  // `iss.labels.includes('18+')` unconditionally, which is how 46 rows ended up
  // disagreeing with the catalogue — hanime.tv's issue carried no label, so a
  // report about an adult source sat on the default board. See nsfwFor.
  const nsfw = nsfwFor(getSource(sourceId), iss.labels);

  let status: string;
  if (iss.state === 'closed') status = 'fixed';
  else if (iss.labels.includes('Valid')) status = 'confirmed';
  else status = 'open';

  // Respect the partial unique index: one open row per source, kind *and*
  // problem. Deduping on kind alone collapsed five distinct failures into one,
  // which is what made a source's second broken thing unfileable.
  const dedupeKey = `${sourceId ?? 'req:' + norm(headOf(iss.title))}|${kind}|${problemKey ?? ''}`;
  const isOpen = status !== 'fixed';
  if (isOpen) {
    if (seenOpen.has(dedupeKey)) status = 'duplicate';
    else seenOpen.add(dedupeKey);
  }

  sourceId ? stats.matched++ : stats.unmatched++;
  stats.byKind[kind] = (stats.byKind[kind] ?? 0) + 1;
  const votes = iss.up + 1; // the reporter counts as the first affected person
  stats.votes += votes;

  out.push(
    `INSERT INTO reports (kind, source_id, proposed_name, proposed_url, lang, nsfw, stage, cause, problem, title, status, reporter_id, github_issue, votes, created_at, updated_at, status_changed_at) VALUES (` +
      [
        esc(kind),
        nul(sourceId ?? null),
        // Requests have no source; unmatched bugs still need a display name.
        !sourceId ? esc(headOf(iss.title).slice(0, 80) || 'Unknown') : 'NULL',
        // The address the request form asked for, out of the issue body. It
        // used to be hardcoded NULL here, which is what left every imported
        // request naming a site it could not identify.
        kind === 'request' ? nul(sourceLinkFromBody(iss.body ?? null)) : 'NULL',
        esc(lang),
        nsfw ? 1 : 0,
        nul(stage),
        nul(cause),
        nul(problemKey),
        esc(problemText),
        esc(status),
        `'0'`,
        iss.number,
        votes,
        ts(iss.createdAt),
        ts(iss.closedAt ?? iss.createdAt),
        iss.closedAt ? ts(iss.closedAt) : 'NULL',
      ].join(', ') +
      ');',
  );
}

console.error(`issues        ${issues.length}`);
console.error(`source match  ${stats.matched} matched / ${stats.unmatched} unmatched`);
console.error(`kinds         ${Object.entries(stats.byKind).map(([k, v]) => `${k}:${v}`).join(' ')}`);
console.error(`votes seeded  ${stats.votes} (from real 👍 reactions + 1 per reporter)`);

console.log(out.join('\n'));
